export const PROJECT_FORM = 'PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const SELECTED_PROJECT = 'SELECTED_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';